// Database constraint details are useful in logs, but not in form responses.
const safeMessages = new Set([
  "Invalid recurrence scope or operation",
  "Invalid recurrence edit fields",
  "Recurring series not found",
  "Occurrence outside active schedule",
  "Series changed; reload and try again",
  "Occurrence does not belong to this series",
  "Future schedule must remain after earlier occurrences",
  "Schedule would recreate a removed occurrence",
  "Completed or awarded Task point settings cannot be edited",
  "Completed or awarded Tasks cannot be removed",
  "Completed or awarded Tasks cannot be archived",
  "Only recurring Task occurrences can be removed",
  "Task has been removed",
  "Idempotency key already used",
  "Admin required",
  "Unauthorized",
  "Officer not found",
  "Event not found",
  "Event is not archived",
  "Event outside branch scope",
  "This event cannot be cancelled",
  "Cannot manage another officer signup for this event",
  "Signups are closed for this event",
  "Target officer is not active",
  "All target officers must be active",
  "This Officer already has an active award for this Event.",
  "Select at least one valid officer",
  "This event cannot accept attendees",
  "Last active admin cannot be deactivated",
  "Admins cannot demote themselves",
  "Last active admin cannot be demoted",
  "Position name is required",
  "Branch name is required",
  "Event type name is required",
  "Position not found",
  "Branch not found",
  "Event type not found",
  "Required positions cannot be renamed",
  "Required positions cannot be deleted",
  "This position cannot be deleted because officers are using it",
  "This branch cannot be deleted because dependent records are using it",
  "This event type cannot be deleted because events are using it",
  "Rate must be a finite positive number",
  "Participation configuration not found",
  "Point transaction not found",
  "Only participation awards can be removed",
  "Invalid point value",
  "Reason required",
  "Event date is required",
  "Name, description and location are required",
  "Invalid event type",
  "Duplicate branches",
  "Events need one date and a valid time from 06:00 through 23:59",
  "This event cannot be edited",
  "Task outside branch scope",
  "Invalid task fields",
  "Task not found",
  "Task is not archived",
  "Cannot assign another officer",
  "Task is not assigned",
  "Only the assignee can complete this task",
  "Task already completed",
  "Task is not awaiting approval",
  "Assignee cannot approve own task",
  "Provide both start and end times",
  "Removed events cannot be edited",
  "Cancelled events cannot be edited",
  "Slides link must be an HTTP(S) URL",
  "Meeting notes link must be an HTTP(S) URL",
  "Event unavailable",
  "Removed transaction cannot be edited",
  "Warning reason is required",
  "Required approvers must have active linked accounts",
  "No eligible approvers remain",
  "Invalid warning decision",
  "Warning not found",
  "You are not an approver for this warning",
  "This approval has already been decided",
  "This warning is already closed",
]);

export function mutationError(message: string) {
  if (message.includes("one_active_primary_event_award_per_officer"))
    return "This Officer already has an active award for this Event.";
  return safeMessages.has(message) ? message : "Could not save changes";
}
