create table public.event_series (
  id bigint generated by default as identity primary key,
  request_key uuid not null unique,
  recurrence_rule text not null check (recurrence_rule ~
    '^RRULE:FREQ=(DAILY|WEEKLY);INTERVAL=[1-9][0-9]*(;BYDAY=(MO|TU|WE|TH|FR|SA|SU)(,(MO|TU|WE|TH|FR|SA|SU))*)?;(COUNT=[1-9][0-9]*|UNTIL=[0-9]{8})$'),
  time_zone text not null default 'America/Denver' check (time_zone='America/Denver'),
  created_by bigint not null references public.officers(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table public.task_series (
  id bigint generated by default as identity primary key,
  request_key uuid not null unique,
  recurrence_rule text not null check (recurrence_rule ~
    '^RRULE:FREQ=(DAILY|WEEKLY);INTERVAL=[1-9][0-9]*(;BYDAY=(MO|TU|WE|TH|FR|SA|SU)(,(MO|TU|WE|TH|FR|SA|SU))*)?;(COUNT=[1-9][0-9]*|UNTIL=[0-9]{8})$'),
  created_by bigint not null references public.officers(id) on delete restrict,
  created_at timestamptz not null default now()
);

alter table public.events
  add column recurrence_series_id bigint references public.event_series(id) on delete restrict,
  add column recurrence_key date,
  add constraint events_recurrence_identity_pair
    check ((recurrence_series_id is null) = (recurrence_key is null));
create unique index event_series_occurrence_key
  on public.events(recurrence_series_id,recurrence_key)
  where recurrence_series_id is not null;

alter table public.tasks
  add column recurrence_series_id bigint references public.task_series(id) on delete restrict,
  add column recurrence_key date,
  add column removed_at timestamptz,
  add column removed_by bigint references public.officers(id) on delete restrict,
  add constraint tasks_recurrence_identity_pair
    check ((recurrence_series_id is null) = (recurrence_key is null)),
  add constraint tasks_removal_actor_pair
    check ((removed_at is null) = (removed_by is null));
create unique index task_series_occurrence_key
  on public.tasks(recurrence_series_id,recurrence_key)
  where recurrence_series_id is not null;
create index tasks_active_due_date_idx on public.tasks(due_date) where removed_at is null;

alter table public.event_series enable row level security;
alter table public.task_series enable row level security;
revoke all on public.event_series,public.task_series from public,anon,authenticated;
grant select on public.event_series,public.task_series to authenticated;
create policy "Approved officers read event series" on public.event_series
  for select to authenticated using ((select private.current_active_officer_id()) is not null);
create policy "Approved officers read task series" on public.task_series
  for select to authenticated using ((select private.current_active_officer_id()) is not null);

create function private.create_recurring_event(
  p_name text,p_description text,p_event_type_id bigint,p_location text,
  p_branch_ids bigint[],p_slides_url text,p_meeting_notes_url text,
  p_request_key uuid,p_recurrence_rule text,p_event_dates date[],
  p_starts_at timestamptz[],p_ends_at timestamptz[]
) returns bigint language plpgsql security definer set search_path = '' as $$
declare actor_id bigint := private.current_active_officer_id(); series_id bigint;
  first_event_id bigint; event_id bigint; i integer; day date;
begin
  if actor_id is null then raise exception 'Unauthorized'; end if;
  if p_recurrence_rule is null or p_recurrence_rule !~
    '^RRULE:FREQ=(DAILY|WEEKLY);INTERVAL=[1-9][0-9]*(;BYDAY=(MO|TU|WE|TH|FR|SA|SU)(,(MO|TU|WE|TH|FR|SA|SU))*)?;(COUNT=[1-9][0-9]*|UNTIL=[0-9]{8})$' then
    raise exception 'Invalid recurrence definition';
  end if;
  if (substring(p_recurrence_rule from 'INTERVAL=([0-9]+)'))::integer>52 or
    (p_recurrence_rule like 'RRULE:FREQ=WEEKLY%' and p_recurrence_rule not like '%;BYDAY=%') or
    (p_recurrence_rule like 'RRULE:FREQ=DAILY%' and p_recurrence_rule like '%;BYDAY=%') then
    raise exception 'Invalid recurrence definition'; end if;
  if p_event_dates is null or cardinality(p_event_dates)<2 or cardinality(p_event_dates)>500 or
    cardinality(p_event_dates)<>cardinality(p_starts_at) or
    cardinality(p_event_dates)<>cardinality(p_ends_at) or
    p_event_dates[1] is null then raise exception 'Invalid recurring Event occurrences'; end if;
  if cardinality(p_event_dates)<>(select count(distinct d) from unnest(p_event_dates) d) or
    p_event_dates[1]<>(select min(d) from unnest(p_event_dates) d) then
    raise exception 'Recurring Event dates must be unique and ordered'; end if;
  if p_recurrence_rule like '%;COUNT=%' and
    ((substring(p_recurrence_rule from ';COUNT=([0-9]+)$'))::integer<2 or
      (substring(p_recurrence_rule from ';COUNT=([0-9]+)$'))::integer>500 or
      cardinality(p_event_dates)<>(substring(p_recurrence_rule from ';COUNT=([0-9]+)$'))::integer) then
    raise exception 'Recurrence count does not match generated occurrences'; end if;
  if p_recurrence_rule like '%;UNTIL=%' and
    p_event_dates[cardinality(p_event_dates)]>(to_date(substring(p_recurrence_rule from ';UNTIL=([0-9]{8})$'),'YYYYMMDD')) then
    raise exception 'Occurrence exceeds recurrence end date'; end if;
  if not private.can_manage_branches(coalesce(p_branch_ids,'{}'::bigint[])) then
    raise exception 'Event outside branch scope'; end if;

  insert into public.event_series(request_key,recurrence_rule,created_by)
    values(p_request_key,p_recurrence_rule,actor_id)
    on conflict(request_key) do nothing returning id into series_id;
  if series_id is null then
    select id into series_id from public.event_series where request_key=p_request_key;
    if (select recurrence_rule from public.event_series where id=series_id) is distinct from p_recurrence_rule or
      (select count(*) from public.events where recurrence_series_id=series_id)<>cardinality(p_event_dates) or
      exists(select 1 from unnest(p_event_dates) d where not exists(
        select 1 from public.events e where e.recurrence_series_id=series_id and e.recurrence_key=d)) then
      raise exception 'Idempotency key already used'; end if;
    select id into first_event_id from public.events
      where recurrence_series_id=series_id and recurrence_key=p_event_dates[1];
    return first_event_id;
  end if;
  for i in 1..cardinality(p_event_dates) loop
    day := p_event_dates[i];
    if day is null or (i>1 and day<=p_event_dates[i-1]) or
      p_starts_at[i] is null or p_ends_at[i] is null or p_ends_at[i]<=p_starts_at[i] or
      (p_starts_at[i] at time zone 'America/Denver')::date<>day or
      (p_ends_at[i] at time zone 'America/Denver')::date<>day then
      raise exception 'Invalid recurring Event schedule'; end if;
    event_id := private.save_event_with_links(p_name,p_description,p_event_type_id,p_location,
      day,p_starts_at[i],p_ends_at[i],p_branch_ids,null,p_slides_url,p_meeting_notes_url);
    update public.events set recurrence_series_id=series_id,recurrence_key=day where id=event_id;
    if first_event_id is null then first_event_id := event_id; end if;
  end loop;
  perform private.write_audit_log('event.series_created','event_series',series_id::text,
    pg_catalog.jsonb_build_object('recurrence_rule',p_recurrence_rule,
      'occurrence_count',cardinality(p_event_dates),'first_event_id',first_event_id));
  return first_event_id;
end;
$$;

create function public.create_recurring_event(
  p_name text,p_description text,p_event_type_id bigint,p_location text,
  p_branch_ids bigint[],p_slides_url text,p_meeting_notes_url text,
  p_request_key uuid,p_recurrence_rule text,p_event_dates date[],
  p_starts_at timestamptz[],p_ends_at timestamptz[]
) returns bigint language sql security invoker set search_path = '' as $$
  select private.create_recurring_event(p_name,p_description,p_event_type_id,p_location,
    p_branch_ids,p_slides_url,p_meeting_notes_url,p_request_key,p_recurrence_rule,
    p_event_dates,p_starts_at,p_ends_at)
$$;

create function private.create_recurring_task(
  p_title text,p_description text,p_task_type text,p_branch_id bigint,p_points numeric,
  p_approval_required boolean,p_request_key uuid,p_recurrence_rule text,p_due_dates date[]
) returns bigint language plpgsql security definer set search_path = '' as $$
declare actor_id bigint := private.current_active_officer_id(); series_id bigint;
  first_task_id bigint; task_id bigint; i integer; day date;
begin
  if actor_id is null then raise exception 'Unauthorized'; end if;
  if p_recurrence_rule is null or p_recurrence_rule !~
    '^RRULE:FREQ=(DAILY|WEEKLY);INTERVAL=[1-9][0-9]*(;BYDAY=(MO|TU|WE|TH|FR|SA|SU)(,(MO|TU|WE|TH|FR|SA|SU))*)?;(COUNT=[1-9][0-9]*|UNTIL=[0-9]{8})$' then
    raise exception 'Invalid recurrence definition';
  end if;
  if (substring(p_recurrence_rule from 'INTERVAL=([0-9]+)'))::integer>52 or
    (p_recurrence_rule like 'RRULE:FREQ=WEEKLY%' and p_recurrence_rule not like '%;BYDAY=%') or
    (p_recurrence_rule like 'RRULE:FREQ=DAILY%' and p_recurrence_rule like '%;BYDAY=%') then
    raise exception 'Invalid recurrence definition'; end if;
  if p_due_dates is null or cardinality(p_due_dates)<2 or cardinality(p_due_dates)>500 or
    cardinality(p_due_dates)<>(select count(distinct d) from unnest(p_due_dates) d) or
    p_due_dates[1]<>(select min(d) from unnest(p_due_dates) d) then
    raise exception 'Invalid recurring Task dates'; end if;
  if p_recurrence_rule like '%;COUNT=%' and
    ((substring(p_recurrence_rule from ';COUNT=([0-9]+)$'))::integer<2 or
      (substring(p_recurrence_rule from ';COUNT=([0-9]+)$'))::integer>500 or
      cardinality(p_due_dates)<>(substring(p_recurrence_rule from ';COUNT=([0-9]+)$'))::integer) then
    raise exception 'Recurrence count does not match generated Tasks'; end if;
  if p_recurrence_rule like '%;UNTIL=%' and
    p_due_dates[cardinality(p_due_dates)]>(to_date(substring(p_recurrence_rule from ';UNTIL=([0-9]{8})$'),'YYYYMMDD')) then
    raise exception 'Task exceeds recurrence end date'; end if;
  if not private.can_manage_branches(array[p_branch_id]) then
    raise exception 'Task outside branch scope'; end if;

  insert into public.task_series(request_key,recurrence_rule,created_by)
    values(p_request_key,p_recurrence_rule,actor_id)
    on conflict(request_key) do nothing returning id into series_id;
  if series_id is null then
    select id into series_id from public.task_series where request_key=p_request_key;
    if (select recurrence_rule from public.task_series where id=series_id) is distinct from p_recurrence_rule or
      (select count(*) from public.tasks where recurrence_series_id=series_id)<>cardinality(p_due_dates) or
      exists(select 1 from unnest(p_due_dates) d where not exists(
        select 1 from public.tasks t where t.recurrence_series_id=series_id and t.recurrence_key=d)) then
      raise exception 'Idempotency key already used'; end if;
    select id into first_task_id from public.tasks
      where recurrence_series_id=series_id and recurrence_key=p_due_dates[1];
    return first_task_id;
  end if;
  for i in 1..cardinality(p_due_dates) loop
    day := p_due_dates[i];
    if day is null or (i>1 and day<=p_due_dates[i-1]) then
      raise exception 'Recurring Task dates must be ordered'; end if;
    task_id := private.save_task(p_title,p_description,p_task_type,p_branch_id,day,
      p_points,p_approval_required);
    update public.tasks set recurrence_series_id=series_id,recurrence_key=day where id=task_id;
    if first_task_id is null then first_task_id := task_id; end if;
  end loop;
  perform private.write_audit_log('task.series_created','task_series',series_id::text,
    pg_catalog.jsonb_build_object('recurrence_rule',p_recurrence_rule,
      'occurrence_count',cardinality(p_due_dates),'first_task_id',first_task_id));
  return first_task_id;
end;
$$;

create function public.create_recurring_task(
  p_title text,p_description text,p_task_type text,p_branch_id bigint,p_points numeric,
  p_approval_required boolean,p_request_key uuid,p_recurrence_rule text,p_due_dates date[]
) returns bigint language sql security invoker set search_path = '' as $$
  select private.create_recurring_task(p_title,p_description,p_task_type,p_branch_id,
    p_points,p_approval_required,p_request_key,p_recurrence_rule,p_due_dates)
$$;

create function private.remove_task(p_task_id bigint) returns void
language plpgsql security definer set search_path = '' as $$
declare task_row public.tasks; actor_id bigint := private.current_active_officer_id();
begin
  if actor_id is null then raise exception 'Unauthorized'; end if;
  select * into task_row from public.tasks where id=p_task_id for update;
  if not found then raise exception 'Task not found'; end if;
  if not private.can_manage_branches(array[task_row.branch_id]) then
    raise exception 'Task outside branch scope'; end if;
  if task_row.removed_at is not null then return; end if;
  if exists(select 1 from public.task_assignments where task_id=p_task_id and completed_at is not null)
    or exists(select 1 from public.point_transactions where task_id=p_task_id and removed_at is null) then
    raise exception 'Completed or awarded Tasks cannot be removed'; end if;
  update public.tasks set removed_at=pg_catalog.clock_timestamp(),removed_by=actor_id where id=p_task_id;
  perform private.write_audit_log('task.removed','task',p_task_id::text,
    pg_catalog.jsonb_build_object('title',task_row.title,'due_date',task_row.due_date,
      'recurrence_series_id',task_row.recurrence_series_id,'recurrence_key',task_row.recurrence_key));
end;
$$;

create function public.remove_task(p_task_id bigint) returns void
language sql security invoker set search_path = '' as $$
  select private.remove_task(p_task_id)
$$;

revoke all on function private.create_recurring_event(text,text,bigint,text,bigint[],text,text,uuid,text,date[],timestamptz[],timestamptz[]),
  public.create_recurring_event(text,text,bigint,text,bigint[],text,text,uuid,text,date[],timestamptz[],timestamptz[]),
  private.create_recurring_task(text,text,text,bigint,numeric,boolean,uuid,text,date[]),
  public.create_recurring_task(text,text,text,bigint,numeric,boolean,uuid,text,date[]),
  private.remove_task(bigint),public.remove_task(bigint)
  from public,anon,authenticated;
grant execute on function public.create_recurring_event(text,text,bigint,text,bigint[],text,text,uuid,text,date[],timestamptz[],timestamptz[]),
  public.create_recurring_task(text,text,text,bigint,numeric,boolean,uuid,text,date[]),
  public.remove_task(bigint) to authenticated;
grant execute on function private.create_recurring_event(text,text,bigint,text,bigint[],text,text,uuid,text,date[],timestamptz[],timestamptz[]),
  private.create_recurring_task(text,text,text,bigint,numeric,boolean,uuid,text,date[]),
  private.remove_task(bigint) to authenticated;
