-- Capture the original hand-created schema so a new database can replay this migration.
create table if not exists public.officers (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  position text not null,
  classification text not null check (classification in ('freshman','sophomore','junior','senior','masters','phd')),
  status text not null default 'active' check (status in ('active','inactive')),
  created_at timestamptz not null default now()
);
create table if not exists public.branches (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);
create table if not exists public.officer_branches (
  officer_id bigint not null references public.officers(id),
  branch_id bigint not null references public.branches(id),
  primary key (officer_id, branch_id)
);
insert into public.branches (name) values ('intro'),('social'),('icpc'),('general') on conflict (name) do nothing;

create table public.positions (
  id bigint generated by default as identity primary key,
  name text not null unique check (length(trim(name)) > 0),
  can_manage_branch_events boolean not null default false,
  created_at timestamptz not null default now()
);
insert into public.positions (name) values
  ('President'),('Vice President of Operations'),('Vice President of Academics'),
  ('Secretary'),('ICPC Lead'),('Intro Lead'),('Chief Outreach'),('Social Media Lead'),
  ('ICPC/Academic Officer'),('Intro/CIC Academic Officer'),('ICPC Officer'),
  ('Intro Academic Officer'),('CIC Academic Officer'),('Outreach Officer'),('Social Media Officer');
-- Preserve existing titles without guessing which new catalog entry they should become.
insert into public.positions (name) select distinct position from public.officers on conflict (name) do nothing;
alter table public.officers add column position_id bigint references public.positions(id);
update public.officers o set position_id = p.id from public.positions p where p.name = o.position;
alter table public.officers alter column position_id set not null;
alter table public.officers drop column position;
alter table public.officers add constraint officers_name_not_blank check (length(trim(name)) > 0);
alter table public.officers add constraint officers_email_not_blank check (length(trim(email)) > 0);
create index officers_position_id_idx on public.officers(position_id);
create index officer_branches_branch_id_idx on public.officer_branches(branch_id);

-- TEMPORARY DEVELOPMENT POLICIES: anonymous reads and only the writes used by this prototype.
-- Replace these with authenticated authorization before production.
alter table public.positions enable row level security;
alter table public.officers enable row level security;
alter table public.branches enable row level security;
alter table public.officer_branches enable row level security;
drop policy if exists read_officers on public.officers;
drop policy if exists read_branches on public.branches;
drop policy if exists read_officer_branches on public.officer_branches;
create policy "TEMPORARY DEVELOPMENT read positions" on public.positions for select to anon using (true);
create policy "TEMPORARY DEVELOPMENT read officers" on public.officers for select to anon using (true);
create policy "TEMPORARY DEVELOPMENT insert officers" on public.officers for insert to anon with check (true);
create policy "TEMPORARY DEVELOPMENT update officers" on public.officers for update to anon using (true) with check (true);
create policy "TEMPORARY DEVELOPMENT read branches" on public.branches for select to anon using (true);
create policy "TEMPORARY DEVELOPMENT read memberships" on public.officer_branches for select to anon using (true);
create policy "TEMPORARY DEVELOPMENT insert memberships" on public.officer_branches for insert to anon with check (true);
create policy "TEMPORARY DEVELOPMENT remove memberships" on public.officer_branches for delete to anon using (true);
revoke all on public.positions, public.officers, public.branches, public.officer_branches from anon, authenticated;
grant select on public.positions, public.branches to anon;
grant select, insert, update on public.officers to anon;
grant select, insert, delete on public.officer_branches to anon;
grant usage on sequence public.officers_id_seq to anon;

-- One database transaction prevents saving an officer without their selected memberships.
create function public.save_officer(
  p_name text, p_email text, p_position_id bigint, p_classification text, p_status text,
  p_branch_ids bigint[], p_officer_id bigint default null
) returns bigint language plpgsql security invoker set search_path = '' as $$
declare saved_id bigint;
begin
  if p_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    raise exception 'Enter a valid email address';
  end if;
  if p_officer_id is null then
    insert into public.officers (name,email,position_id,classification,status)
    values (trim(p_name),lower(trim(p_email)),p_position_id,p_classification,p_status)
    returning id into saved_id;
  else
    update public.officers set name=trim(p_name),email=lower(trim(p_email)),position_id=p_position_id,
      classification=p_classification,status=p_status where id=p_officer_id returning id into saved_id;
    if saved_id is null then raise exception 'Officer not found'; end if;
  end if;
  delete from public.officer_branches where officer_id=saved_id;
  insert into public.officer_branches (officer_id,branch_id)
  select saved_id, branch_id from unnest(p_branch_ids) as branch_id;
  return saved_id;
end;
$$;
revoke all on function public.save_officer(text,text,bigint,text,text,bigint[],bigint) from public;
grant execute on function public.save_officer(text,text,bigint,text,text,bigint[],bigint) to anon;
