-- Issue #178: native Event capacity and a separate FIFO waitlist.
alter table public.events
  add column max_volunteers integer check (max_volunteers is null or max_volunteers > 0);

create table public.event_waitlist (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  officer_id bigint not null references public.officers(id) on delete cascade,
  joined_at timestamptz not null default pg_catalog.clock_timestamp(),
  unique (event_id, officer_id)
);
create index event_waitlist_fifo_idx on public.event_waitlist(event_id, joined_at, id);
alter table public.event_waitlist enable row level security;
revoke all on public.event_waitlist from public, anon, authenticated;
grant select on public.event_waitlist to authenticated;
grant execute on function private.can_manage_event(bigint) to authenticated;
create policy "Officers read own waitlist entries and managers read queue"
  on public.event_waitlist for select to authenticated
  using (
    officer_id = (select private.current_active_officer_id())
    or private.can_manage_event(event_id)
  );

-- Public reads return counts only. Waitlist identities remain visible only to
-- the waiting Officer and authorized Event managers through the table policy.
create function public.event_signup_counts()
returns table(event_id bigint, confirmed_count bigint, waitlist_count bigint)
language sql security definer set search_path = '' as $$
  select e.id,
    (select count(*) from public.event_officers eo where eo.event_id=e.id),
    (select count(*) from public.event_waitlist ew where ew.event_id=e.id)
  from public.events e
  where private.current_active_officer_id() is not null
$$;
revoke all on function public.event_signup_counts() from public, anon, authenticated;
grant execute on function public.event_signup_counts() to authenticated;

create function private.prevent_event_signup_overlap()
returns trigger language plpgsql security definer set search_path = '' as $$
declare capacity integer; confirmed_count bigint; officer_active boolean;
begin
  if tg_table_name = 'event_officers' then
    if tg_op='UPDATE' and new.event_id=old.event_id and new.officer_id=old.officer_id then
      return new;
    end if;
    select max_volunteers into capacity from public.events where id=new.event_id for update;
    if not found then raise exception 'Event not found'; end if;
    confirmed_count := (select count(*) from public.event_officers eo where eo.event_id=new.event_id);
    if capacity is not null and confirmed_count>=capacity then
      raise exception 'Event capacity has been reached';
    end if;
    if exists(select 1 from public.event_waitlist w
      where w.event_id=new.event_id and w.officer_id=new.officer_id) then
      raise exception 'Officer is already on this Event waitlist';
    end if;
  else
    select max_volunteers into capacity from public.events where id=new.event_id for update;
    if not found then raise exception 'Event not found'; end if;
    if capacity is null then raise exception 'Unlimited Events cannot have a waitlist'; end if;
    confirmed_count := (select count(*) from public.event_officers eo where eo.event_id=new.event_id);
    if confirmed_count<capacity then raise exception 'Event still has confirmed capacity'; end if;
    select status='active' into officer_active from public.officers where id=new.officer_id for share;
    if not coalesce(officer_active,false) then raise exception 'Target officer is not active'; end if;
    if exists(select 1 from public.event_officers eo
      where eo.event_id=new.event_id and eo.officer_id=new.officer_id) then
      raise exception 'Officer is already confirmed for this Event';
    end if;
  end if;
  return new;
end;
$$;
create trigger event_officers_no_waitlist_overlap
  before insert or update of event_id, officer_id on public.event_officers
  for each row execute function private.prevent_event_signup_overlap();
create trigger event_waitlist_no_confirmed_overlap
  before insert or update of event_id, officer_id on public.event_waitlist
  for each row execute function private.prevent_event_signup_overlap();
revoke all on function private.prevent_event_signup_overlap() from public, anon, authenticated;

create function private.promote_event_waitlist(p_event_id bigint)
returns integer language plpgsql security definer set search_path = '' as $$
declare event_row public.events%rowtype; candidate record; candidate_active boolean;
  confirmed_count bigint; promoted integer := 0;
begin
  select * into event_row from public.events where id=p_event_id for update;
  if not found then raise exception 'Event not found'; end if;
  confirmed_count := (select count(*) from public.event_officers where event_id=p_event_id);
  for candidate in select w.id,w.officer_id,w.joined_at from public.event_waitlist w
    where w.event_id=p_event_id order by w.joined_at,w.id
  loop
    select status='active' into candidate_active from public.officers
      where id=candidate.officer_id for share;
    if not coalesce(candidate_active,false) then
      delete from public.event_waitlist where id=candidate.id;
    elsif event_row.max_volunteers is null or confirmed_count < event_row.max_volunteers then
      delete from public.event_waitlist where id=candidate.id;
      insert into public.event_officers(event_id,officer_id)
        values(p_event_id,candidate.officer_id);
      confirmed_count := confirmed_count + 1;
      promoted := promoted + 1;
      perform private.write_audit_log('event.waitlist_promoted','event',p_event_id::text,
        pg_catalog.jsonb_build_object('event_id',p_event_id,'officer_id',candidate.officer_id,
          'waitlist_id',candidate.id,'joined_at',candidate.joined_at));
    end if;
  end loop;
  return promoted;
end;
$$;
revoke all on function private.promote_event_waitlist(bigint) from public, anon, authenticated;

create function private.set_event_capacity(p_event_id bigint,p_max_volunteers integer)
returns void language plpgsql security definer set search_path = '' as $$
declare event_row public.events%rowtype; confirmed_count bigint;
begin
  if private.current_active_officer_id() is null then raise exception 'Unauthorized'; end if;
  if p_max_volunteers is not null and p_max_volunteers <= 0 then
    raise exception 'Max volunteers must be a positive whole number';
  end if;
  select * into event_row from public.events where id=p_event_id for update;
  if not found then raise exception 'Event not found'; end if;
  if not private.can_manage_event(p_event_id) then raise exception 'Event outside branch scope'; end if;
  confirmed_count := (select count(*) from public.event_officers where event_id=p_event_id);
  if p_max_volunteers is not null and p_max_volunteers < confirmed_count then
    raise exception 'Max volunteers cannot be lower than the confirmed signup count';
  end if;
  if event_row.max_volunteers is distinct from p_max_volunteers then
    update public.events set max_volunteers=p_max_volunteers where id=p_event_id;
    perform private.write_audit_log('event.capacity_changed','event',p_event_id::text,
      pg_catalog.jsonb_build_object('event_id',p_event_id,'before',
        pg_catalog.jsonb_build_object('max_volunteers',event_row.max_volunteers),
        'after',pg_catalog.jsonb_build_object('max_volunteers',p_max_volunteers)));
  end if;
  perform private.promote_event_waitlist(p_event_id);
end;
$$;
revoke all on function private.set_event_capacity(bigint,integer) from public, anon, authenticated;

create or replace function private.change_event_signup(
  p_event_id bigint,p_officer_id bigint,p_remove boolean
) returns void language plpgsql security definer set search_path = '' as $$
declare current_event public.events%rowtype; actor_id bigint := private.current_active_officer_id();
  changed_rows integer; confirmed_count bigint; waitlist_id bigint;
begin
  if actor_id is null then raise exception 'Unauthorized'; end if;
  select * into current_event from public.events where id=p_event_id for update;
  if not found then raise exception 'Event not found'; end if;
  if current_event.deleted_at is not null or current_event.status='cancelled' or
    current_event.participation_points_per_hour_at_end is not null or current_event.ends_at<=pg_catalog.now() then
    raise exception 'Signups are closed for this event'; end if;
  if p_officer_id is distinct from actor_id and not private.can_manage_event(p_event_id) then
    raise exception 'Cannot manage another officer signup for this event'; end if;
  perform 1 from public.officers where id=p_officer_id and status='active' for share;
  if not found then raise exception 'Target officer is not active'; end if;
  if p_remove then
    delete from public.event_officers where event_id=p_event_id and officer_id=p_officer_id;
    get diagnostics changed_rows=row_count;
    if changed_rows>0 then perform private.promote_event_waitlist(p_event_id); end if;
  elsif exists(select 1 from public.event_officers where event_id=p_event_id and officer_id=p_officer_id) then
    changed_rows := 0;
  else
    confirmed_count := (select count(*) from public.event_officers where event_id=p_event_id);
    if current_event.max_volunteers is not null and confirmed_count>=current_event.max_volunteers then
      insert into public.event_waitlist(event_id,officer_id) values(p_event_id,p_officer_id)
        on conflict(event_id,officer_id) do nothing returning id into waitlist_id;
      get diagnostics changed_rows=row_count;
      if changed_rows>0 then perform private.write_audit_log('event.waitlist_joined','event',p_event_id::text,
        pg_catalog.jsonb_build_object('event_id',p_event_id,'officer_id',p_officer_id,
          'waitlist_id',waitlist_id,'joined_at',(select joined_at from public.event_waitlist where id=waitlist_id))); end if;
      return;
    end if;
    insert into public.event_officers(event_id,officer_id) values(p_event_id,p_officer_id)
      on conflict(event_id,officer_id) do nothing;
    get diagnostics changed_rows=row_count;
  end if;
  if changed_rows>0 then
    perform private.write_audit_log(case when p_remove and p_officer_id=actor_id then 'event.signout'
      when p_remove then 'event.officer_removed' when p_officer_id=actor_id then 'event.signup'
      else 'event.officer_assigned' end,'event',p_event_id::text,
      pg_catalog.jsonb_build_object('officer_id',p_officer_id,'actor_id',actor_id,'removed',p_remove));
  end if;
end;
$$;

create function private.leave_event_waitlist(p_event_id bigint,p_officer_id bigint)
returns void language plpgsql security definer set search_path = '' as $$
declare event_row public.events%rowtype; actor_id bigint := private.current_active_officer_id();
  old_entry public.event_waitlist%rowtype;
begin
  if actor_id is null then raise exception 'Unauthorized'; end if;
  select * into event_row from public.events where id=p_event_id for update;
  if not found then raise exception 'Event not found'; end if;
  if event_row.deleted_at is not null or event_row.status='cancelled' or
    event_row.participation_points_per_hour_at_end is not null or event_row.ends_at<=pg_catalog.now() then
    raise exception 'Waitlist is closed for this event'; end if;
  if p_officer_id is distinct from actor_id and not private.can_manage_event(p_event_id) then
    raise exception 'Cannot manage another officer waitlist entry for this event'; end if;
  select * into old_entry from public.event_waitlist where event_id=p_event_id
    and officer_id=p_officer_id for update;
  if not found then return; end if;
  delete from public.event_waitlist where id=old_entry.id;
  perform private.write_audit_log('event.waitlist_left','event',p_event_id::text,
    pg_catalog.jsonb_build_object('event_id',p_event_id,'officer_id',p_officer_id,
      'waitlist_id',old_entry.id,'joined_at',old_entry.joined_at,'actor_id',actor_id));
end;
$$;

create function public.leave_event_waitlist(p_event_id bigint,p_officer_id bigint)
returns void language sql security invoker set search_path = '' as $$
  select private.leave_event_waitlist(p_event_id,p_officer_id)
$$;
revoke all on function private.leave_event_waitlist(bigint,bigint),
  public.leave_event_waitlist(bigint,bigint) from public,anon,authenticated;
grant execute on function private.leave_event_waitlist(bigint,bigint),
  public.leave_event_waitlist(bigint,bigint) to authenticated;

-- The bulk manager path also writes the canonical confirmed roster and can
-- process past attendance, so reject a request that would exceed capacity.
create or replace function private.bulk_add_event_officers(
  p_event_id bigint,p_officer_ids bigint[]
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare current_event public.events%rowtype; actor_id bigint := private.current_active_officer_id();
  requested_ids bigint[]; added_ids bigint[]; award_targets bigint[];
  awarded_ids bigint[] := '{}'::bigint[]; target_id bigint; current_rate numeric;
  award_points numeric; scheduled_hours numeric; award_id bigint; snapshot_created boolean := false;
  confirmed_count bigint; new_count bigint;
begin
  if actor_id is null then raise exception 'Unauthorized'; end if;
  if p_officer_ids is null or cardinality(p_officer_ids)=0 or array_position(p_officer_ids,null) is not null then
    raise exception 'Select at least one valid officer'; end if;
  select array_agg(id order by id) into requested_ids from
    (select distinct unnest(p_officer_ids) as id) submitted;
  select * into current_event from public.events where id=p_event_id for update;
  if not found then raise exception 'Event not found'; end if;
  if not private.can_manage_event(p_event_id) then raise exception 'Event outside branch scope'; end if;
  if current_event.deleted_at is not null or current_event.status='cancelled' then
    raise exception 'This event cannot accept attendees'; end if;
  perform o.id from public.officers o where o.id=any(requested_ids) and o.status='active'
    order by o.id for share;
  if (select count(*) from public.officers o where o.id=any(requested_ids) and o.status='active')<>cardinality(requested_ids) then
    raise exception 'All target officers must be active'; end if;
  if exists(select 1 from public.event_waitlist w where w.event_id=p_event_id and w.officer_id=any(requested_ids)) then
    raise exception 'Waitlisted Officers must be promoted in FIFO order'; end if;
  confirmed_count := (select count(*) from public.event_officers where event_id=p_event_id);
  new_count := (select count(*) from unnest(requested_ids) id where not exists(
    select 1 from public.event_officers eo where eo.event_id=p_event_id and eo.officer_id=id));
  if current_event.max_volunteers is not null and confirmed_count+new_count>current_event.max_volunteers then
    raise exception 'The selected Officers exceed the Event capacity'; end if;
  with inserted as (
    insert into public.event_officers(event_id,officer_id)
    select p_event_id,id from unnest(requested_ids) submitted(id)
    on conflict(event_id,officer_id) do nothing returning officer_id
  ) select coalesce(array_agg(officer_id order by officer_id),'{}'::bigint[]) into added_ids from inserted;
  if current_event.ends_at<=pg_catalog.now() then
    current_rate := current_event.participation_points_per_hour_at_end;
    if current_rate is null then
      select participation_points_per_hour into current_rate from public.application_config where id=1 for share;
      if not found then raise exception 'Participation configuration not found'; end if;
      update public.events set participation_points_per_hour_at_end=current_rate where id=p_event_id;
      snapshot_created := true;
    end if;
    scheduled_hours := extract(epoch from (current_event.ends_at-current_event.starts_at))::numeric/3600;
    award_points := private.event_participation_points(current_event.starts_at,current_event.ends_at,current_rate);
    if snapshot_created then
      select coalesce(array_agg(officer_id order by officer_id),'{}'::bigint[]) into award_targets
        from public.event_officers where event_id=p_event_id;
    else award_targets := requested_ids; end if;
    foreach target_id in array award_targets loop
      award_id := null;
      insert into public.point_transactions(officer_id,event_id,points,reason,award_type,created_by)
      values(target_id,p_event_id,award_points,'Event participation','participation',null)
      on conflict do nothing returning id into award_id;
      if award_id is not null then
        awarded_ids := pg_catalog.array_append(awarded_ids,target_id);
        perform private.write_audit_log('points.participation_created','point_transaction',award_id::text,
          pg_catalog.jsonb_build_object('transaction_id',award_id,'event_id',p_event_id,'officer_id',target_id,
            'scheduled_hours',scheduled_hours,'rate',current_rate,'points',award_points));
      elsif exists(select 1 from public.point_transactions where officer_id=target_id and event_id=p_event_id
        and award_type='manual' and removed_at is null) then
        raise exception 'This Officer already has an active award for this Event.';
      end if;
    end loop;
  end if;
  if cardinality(added_ids)>0 or cardinality(awarded_ids)>0 or snapshot_created then
    perform private.write_audit_log('event.officers_bulk_added','event',p_event_id::text,
      pg_catalog.jsonb_build_object('event_id',p_event_id,'actor_id',actor_id,'officer_ids',added_ids,
        'participation_awards_created',awarded_ids,'participation_rate',current_rate,
        'points_per_officer',award_points,'scheduled_hours',scheduled_hours));
  end if;
  return pg_catalog.jsonb_build_object('event_id',p_event_id,'added_officer_ids',added_ids,
    'awarded_officer_ids',awarded_ids,'rate',current_rate,'points_per_officer',award_points);
end;
$$;

-- Preserve established RPCs for already deployed clients. The new form calls
-- this atomic wrapper so Event details, link fields, and capacity commit once.
create function private.save_event_with_capacity(
  p_name text,p_description text,p_event_type_id bigint,p_location text,p_event_date date,
  p_starts_at timestamptz,p_ends_at timestamptz,p_branch_ids bigint[],p_signup_sheet_url text,
  p_max_volunteers integer default 0,p_event_id bigint default null,p_slides_url text default null,
  p_meeting_notes_url text default null
) returns bigint language plpgsql security definer set search_path = '' as $$
declare saved_id bigint;
begin
  saved_id := private.save_event_with_signup_sheet(p_name,p_description,p_event_type_id,p_location,
    p_event_date,p_starts_at,p_ends_at,p_branch_ids,p_event_id,p_slides_url,p_meeting_notes_url,p_signup_sheet_url);
  if p_max_volunteers<0 then raise exception 'Max volunteers must be a positive whole number'; end if;
  perform private.set_event_capacity(saved_id,nullif(p_max_volunteers,0));
  return saved_id;
end;
$$;
create function public.save_event_with_capacity(
  p_name text,p_description text,p_event_type_id bigint,p_location text,p_event_date date,
  p_starts_at timestamptz,p_ends_at timestamptz,p_branch_ids bigint[],p_signup_sheet_url text,
  p_max_volunteers integer default 0,p_event_id bigint default null,p_slides_url text default null,
  p_meeting_notes_url text default null
) returns bigint language sql security invoker set search_path = '' as $$
  select private.save_event_with_capacity(p_name,p_description,p_event_type_id,p_location,
    p_event_date,p_starts_at,p_ends_at,p_branch_ids,p_signup_sheet_url,p_max_volunteers,
    p_event_id,p_slides_url,p_meeting_notes_url)
$$;
revoke all on function private.save_event_with_capacity(text,text,bigint,text,date,timestamptz,timestamptz,bigint[],text,integer,bigint,text,text),
  public.save_event_with_capacity(text,text,bigint,text,date,timestamptz,timestamptz,bigint[],text,integer,bigint,text,text)
  from public,anon,authenticated;
grant execute on function private.save_event_with_capacity(text,text,bigint,text,date,timestamptz,timestamptz,bigint[],text,integer,bigint,text,text),
  public.save_event_with_capacity(text,text,bigint,text,date,timestamptz,timestamptz,bigint[],text,integer,bigint,text,text)
  to authenticated;

create table private.recurring_event_capacity_requests (
  request_key uuid primary key,
  first_event_id bigint not null references public.events(id) on delete cascade,
  max_volunteers integer check(max_volunteers is null or max_volunteers>0)
);
revoke all on private.recurring_event_capacity_requests from public,anon,authenticated;

create function private.create_recurring_event_with_capacity(
  p_name text,p_description text,p_event_type_id bigint,p_location text,p_branch_ids bigint[],
  p_slides_url text,p_meeting_notes_url text,p_signup_sheet_url text,p_max_volunteers integer,
  p_request_key uuid,p_recurrence_rule text,p_event_dates date[],p_starts_at timestamptz[],p_ends_at timestamptz[]
) returns bigint language plpgsql security definer set search_path = '' as $$
declare first_id bigint; series_id bigint; prior_limit integer; prior_event_id bigint; had_receipt boolean;
begin
  if p_max_volunteers<0 then
    raise exception 'Max volunteers must be a positive whole number'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_request_key::text,73));
  select max_volunteers,first_event_id into prior_limit,prior_event_id from private.recurring_event_capacity_requests
    where request_key=p_request_key for update;
  had_receipt := found;
  if had_receipt then
    if prior_limit is distinct from nullif(p_max_volunteers,0) then raise exception 'Idempotency key already used'; end if;
    first_id := public.create_recurring_event(p_name,p_description,p_event_type_id,p_location,
      p_branch_ids,p_slides_url,p_meeting_notes_url,p_signup_sheet_url,p_request_key,
      p_recurrence_rule,p_event_dates,p_starts_at,p_ends_at);
    if first_id is distinct from prior_event_id then raise exception 'Idempotency key already used'; end if;
    return first_id;
  end if;
  first_id := public.create_recurring_event(p_name,p_description,p_event_type_id,p_location,
    p_branch_ids,p_slides_url,p_meeting_notes_url,p_signup_sheet_url,p_request_key,
    p_recurrence_rule,p_event_dates,p_starts_at,p_ends_at);
  select recurrence_series_id into series_id from public.events where id=first_id;
  insert into private.recurring_event_capacity_requests(request_key,first_event_id,max_volunteers)
    values(p_request_key,first_id,nullif(p_max_volunteers,0));
  for first_id in select id from public.events where recurrence_series_id=series_id order by recurrence_key loop
    perform private.set_event_capacity(first_id,nullif(p_max_volunteers,0));
  end loop;
  select id into first_id from public.events where recurrence_series_id=series_id
    order by recurrence_key limit 1;
  return first_id;
end;
$$;

create table private.recurring_event_capacity_mutations (
  request_key uuid primary key,
  max_volunteers integer check(max_volunteers is null or max_volunteers>0)
);
revoke all on private.recurring_event_capacity_mutations from public,anon,authenticated;
create function public.create_recurring_event_with_capacity(
  p_name text,p_description text,p_event_type_id bigint,p_location text,p_branch_ids bigint[],
  p_slides_url text,p_meeting_notes_url text,p_signup_sheet_url text,p_max_volunteers integer,
  p_request_key uuid,p_recurrence_rule text,p_event_dates date[],p_starts_at timestamptz[],p_ends_at timestamptz[]
) returns bigint language sql security invoker set search_path = '' as $$
  select private.create_recurring_event_with_capacity(p_name,p_description,p_event_type_id,p_location,
    p_branch_ids,p_slides_url,p_meeting_notes_url,p_signup_sheet_url,p_max_volunteers,
    p_request_key,p_recurrence_rule,p_event_dates,p_starts_at,p_ends_at)
$$;
revoke all on function private.create_recurring_event_with_capacity(text,text,bigint,text,bigint[],text,text,text,integer,uuid,text,date[],timestamptz[],timestamptz[]),
  public.create_recurring_event_with_capacity(text,text,bigint,text,bigint[],text,text,text,integer,uuid,text,date[],timestamptz[],timestamptz[])
  from public,anon,authenticated;
grant execute on function private.create_recurring_event_with_capacity(text,text,bigint,text,bigint[],text,text,text,integer,uuid,text,date[],timestamptz[],timestamptz[]),
  public.create_recurring_event_with_capacity(text,text,bigint,text,bigint[],text,text,text,integer,uuid,text,date[],timestamptz[],timestamptz[])
  to authenticated;

create function private.mutate_recurring_event_with_capacity(
  p_selected_id bigint,p_scope text,p_operation text,p_request_key uuid,p_series_id bigint,
  p_revision integer,p_patch jsonb,p_rule text,p_dates date[],p_capacity_changed boolean,
  p_max_volunteers integer
) returns bigint language plpgsql security definer set search_path = '' as $$
declare selected_id bigint; selected_event public.events%rowtype; target_id bigint;
  prior_limit integer; had_receipt boolean;
begin
  if p_capacity_changed and p_max_volunteers<0 then
    raise exception 'Max volunteers must be a positive whole number'; end if;
  selected_id := private.mutate_recurring_event(p_selected_id,p_scope,p_operation,p_request_key,
    p_series_id,p_revision,p_patch,p_rule,p_dates);
  if p_capacity_changed then
    select max_volunteers into prior_limit from private.recurring_event_capacity_mutations
      where request_key=p_request_key for update;
    had_receipt := found;
    if had_receipt and prior_limit is distinct from nullif(p_max_volunteers,0) then
      raise exception 'Idempotency key already used';
    end if;
    if not had_receipt then
      insert into private.recurring_event_capacity_mutations(request_key,max_volunteers)
        values(p_request_key,nullif(p_max_volunteers,0));
    end if;
    select * into selected_event from public.events where id=selected_id for update;
    if p_scope='occurrence' then
      perform private.set_event_capacity(selected_id,nullif(p_max_volunteers,0));
    else
      for target_id in select id from public.events where recurrence_series_id=selected_event.recurrence_series_id
        and (p_scope='series' or recurrence_key>=selected_event.recurrence_key)
        and deleted_at is null order by recurrence_key,id
      loop perform private.set_event_capacity(target_id,nullif(p_max_volunteers,0)); end loop;
    end if;
  end if;
  return selected_id;
end;
$$;
create function public.mutate_recurring_event_with_capacity(
  p_selected_id bigint,p_scope text,p_operation text,p_request_key uuid,p_series_id bigint,
  p_revision integer,p_patch jsonb default '{}',p_rule text default null,p_dates date[] default null,
  p_capacity_changed boolean default false,p_max_volunteers integer default 0
) returns bigint language sql security invoker set search_path = '' as $$
  select private.mutate_recurring_event_with_capacity(p_selected_id,p_scope,p_operation,
    p_request_key,p_series_id,p_revision,p_patch,p_rule,p_dates,p_capacity_changed,p_max_volunteers)
$$;
revoke all on function private.mutate_recurring_event_with_capacity(bigint,text,text,uuid,bigint,integer,jsonb,text,date[],boolean,integer),
  public.mutate_recurring_event_with_capacity(bigint,text,text,uuid,bigint,integer,jsonb,text,date[],boolean,integer)
  from public,anon,authenticated;
grant execute on function private.mutate_recurring_event_with_capacity(bigint,text,text,uuid,bigint,integer,jsonb,text,date[],boolean,integer),
  public.mutate_recurring_event_with_capacity(bigint,text,text,uuid,bigint,integer,jsonb,text,date[],boolean,integer)
  to authenticated;

-- Update selected Event field edits without changing recurrence scope rules.
revoke all on function public.change_event_signup(bigint,bigint,boolean) from public,anon,authenticated;
grant execute on function public.change_event_signup(bigint,bigint,boolean) to authenticated;
revoke all on function private.change_event_signup(bigint,bigint,boolean) from public,anon,authenticated;
grant execute on function private.change_event_signup(bigint,bigint,boolean) to authenticated;
revoke all on function public.bulk_add_event_officers(bigint,bigint[]) from public,anon,authenticated;
grant execute on function public.bulk_add_event_officers(bigint,bigint[]) to authenticated;
revoke all on function private.bulk_add_event_officers(bigint,bigint[]) from public,anon,authenticated;
grant execute on function private.bulk_add_event_officers(bigint,bigint[]) to authenticated;
