create table public.point_transactions (
 id bigint generated by default as identity primary key,
 officer_id bigint not null references public.officers(id),
 event_id bigint references public.events(id),
 points numeric not null check(points not in ('NaN'::numeric,'Infinity'::numeric,'-Infinity'::numeric)),
 reason text not null check(length(trim(reason))>0),
 award_type text not null check(award_type in ('participation','manual','correction')),
 created_by uuid, created_at timestamptz not null default now(),
 check(award_type<>'participation' or event_id is not null)
);
-- Repeated or simultaneous processing cannot award the same signup twice.
create unique index one_participation_award on public.point_transactions(officer_id,event_id) where award_type='participation';
create index point_transactions_event_id_idx on public.point_transactions(event_id);
create index point_transactions_created_at_idx on public.point_transactions(created_at);
alter table public.point_transactions enable row level security;
create policy "TEMPORARY DEVELOPMENT read points" on public.point_transactions for select to anon using(true);
create policy "TEMPORARY DEVELOPMENT insert points" on public.point_transactions for insert to anon with check(created_by is null);
revoke all on public.point_transactions from anon,authenticated;
grant select,insert on public.point_transactions to anon;
grant usage on sequence public.point_transactions_id_seq to anon;
-- Totals are a query, never a second stored value to keep synchronized.
create view public.officer_point_totals with(security_invoker=true) as
 select o.id,o.name,coalesce(sum(p.points),0) as total_points
 from public.officers o left join public.point_transactions p on p.officer_id=o.id group by o.id,o.name;
grant select on public.officer_point_totals to anon;
create function public.process_completed_events(p_points_per_hour numeric)
returns integer language plpgsql security invoker set search_path='' as $$
declare inserted_count integer;
begin
 if p_points_per_hour is null or p_points_per_hour<=0 or p_points_per_hour in ('NaN'::numeric,'Infinity'::numeric) then raise exception 'Points per hour must be a finite positive number'; end if;
 insert into public.point_transactions(officer_id,event_id,points,reason,award_type)
 select signup.officer_id,event.id,extract(epoch from (event.ends_at-event.starts_at))/3600*p_points_per_hour,
 'Scheduled event participation','participation'
 from public.events event join public.event_officers signup on signup.event_id=event.id
 where event.ends_at<=now() and event.status<>'cancelled'
 on conflict(officer_id,event_id) where award_type='participation' do nothing;
 get diagnostics inserted_count=row_count;
 return inserted_count;
end; $$;
revoke all on function public.process_completed_events(numeric) from public;
grant execute on function public.process_completed_events(numeric) to anon;
