create table public.events (
 id bigint generated by default as identity primary key,
 name text not null check(length(trim(name))>0),
 description text not null default '', type text not null check(length(trim(type))>0),
 location text, starts_at timestamptz not null, ends_at timestamptz not null,
 status text not null default 'upcoming' check(status in ('upcoming','happening','past','cancelled')),
 created_at timestamptz not null default now(), check(ends_at>starts_at)
);
create table public.event_branches (
 event_id bigint not null references public.events(id), branch_id bigint not null references public.branches(id),
 primary key(event_id,branch_id)
);
create table public.event_officers (
 event_id bigint not null references public.events(id), officer_id bigint not null references public.officers(id),
 primary key(event_id,officer_id)
);
create index event_branches_branch_id_idx on public.event_branches(branch_id);
create index event_officers_officer_id_idx on public.event_officers(officer_id);
create index events_starts_at_idx on public.events(starts_at);
-- TEMPORARY DEVELOPMENT POLICIES; replace with authenticated permissions before production.
alter table public.events enable row level security;
alter table public.event_branches enable row level security;
alter table public.event_officers enable row level security;
create policy "TEMPORARY DEVELOPMENT read events" on public.events for select to anon using(true);
create policy "TEMPORARY DEVELOPMENT create events" on public.events for insert to anon with check(true);
create policy "TEMPORARY DEVELOPMENT update future events" on public.events for update to anon using(ends_at>now()) with check(true);
create policy "TEMPORARY DEVELOPMENT read event branches" on public.event_branches for select to anon using(true);
create policy "TEMPORARY DEVELOPMENT insert event branches" on public.event_branches for insert to anon with check(true);
create policy "TEMPORARY DEVELOPMENT remove event branches" on public.event_branches for delete to anon using(true);
create policy "TEMPORARY DEVELOPMENT read signups" on public.event_officers for select to anon using(true);
create policy "TEMPORARY DEVELOPMENT add signups" on public.event_officers for insert to anon with check(exists(select 1 from public.events e where e.id=event_id and e.ends_at>now() and e.status<>'cancelled'));
create policy "TEMPORARY DEVELOPMENT remove signups" on public.event_officers for delete to anon using(exists(select 1 from public.events e where e.id=event_id and e.ends_at>now() and e.status<>'cancelled'));
revoke all on public.events,public.event_branches,public.event_officers from anon,authenticated;
grant select,insert,update on public.events to anon;
grant select,insert,delete on public.event_branches,public.event_officers to anon;
grant usage on sequence public.events_id_seq to anon;
create function public.save_event(p_name text,p_description text,p_type text,p_location text,p_starts_at timestamptz,p_ends_at timestamptz,p_branch_ids bigint[],p_event_id bigint default null)
returns bigint language plpgsql security invoker set search_path='' as $$
declare saved_id bigint; current_event public.events;
begin
 if coalesce(cardinality(p_branch_ids),0)=0 then raise exception 'Select at least one branch'; end if;
 if p_event_id is null then
  insert into public.events(name,description,type,location,starts_at,ends_at) values(trim(p_name),p_description,trim(p_type),nullif(trim(p_location),''),p_starts_at,p_ends_at) returning id into saved_id;
 else
  select * into current_event from public.events where id=p_event_id for update;
  if not found then raise exception 'Event not found'; end if;
  if current_event.starts_at<=now() or current_event.status='cancelled' then raise exception 'Only upcoming events can be edited'; end if;
  update public.events set name=trim(p_name),description=p_description,type=trim(p_type),location=nullif(trim(p_location),''),starts_at=p_starts_at,ends_at=p_ends_at where id=p_event_id returning id into saved_id;
 end if;
 delete from public.event_branches where event_id=saved_id;
 insert into public.event_branches(event_id,branch_id) select saved_id,branch_id from unnest(p_branch_ids) as branch_id;
 return saved_id;
end; $$;
create function public.change_event_signup(p_event_id bigint,p_officer_id bigint,p_remove boolean default false)
returns void language plpgsql security invoker set search_path='' as $$
declare current_event public.events;
begin
 select * into current_event from public.events where id=p_event_id for update;
 if not found then raise exception 'Event not found'; end if;
 if current_event.ends_at<=now() or current_event.status='cancelled' then raise exception 'Signups are closed for this event'; end if;
 if p_remove then delete from public.event_officers where event_id=p_event_id and officer_id=p_officer_id;
 else insert into public.event_officers(event_id,officer_id) values(p_event_id,p_officer_id) on conflict do nothing; end if;
end; $$;
revoke all on function public.save_event(text,text,text,text,timestamptz,timestamptz,bigint[],bigint) from public;
revoke all on function public.change_event_signup(bigint,bigint,boolean) from public;
grant execute on function public.save_event(text,text,text,text,timestamptz,timestamptz,bigint[],bigint),public.change_event_signup(bigint,bigint,boolean) to anon;
