-- Event.location remains a text snapshot so renaming or removing a reusable
-- location never rewrites historical Events. The optional FK points to the
-- current autocomplete entry and is safe to clear when that entry is deleted.
create table public.event_locations (
  id bigint generated by default as identity primary key,
  name text not null check (length(pg_catalog.btrim(name)) > 0),
  normalized_name text generated always as (
    pg_catalog.lower(pg_catalog.regexp_replace(
      pg_catalog.btrim(name), '[[:space:]]+', ' ', 'g'
    ))
  ) stored unique,
  created_at timestamptz not null default pg_catalog.now()
);

insert into public.event_locations(name)
select distinct on (
  pg_catalog.lower(pg_catalog.regexp_replace(
    pg_catalog.btrim(location), '[[:space:]]+', ' ', 'g'
  ))
) pg_catalog.btrim(location)
from public.events
where location is not null and length(pg_catalog.btrim(location)) > 0
order by pg_catalog.lower(pg_catalog.regexp_replace(
  pg_catalog.btrim(location), '[[:space:]]+', ' ', 'g'
)), pg_catalog.btrim(location);

alter table public.events add column location_id bigint
  references public.event_locations(id) on delete set null;

update public.events e set location_id = l.id
from public.event_locations l
where l.normalized_name = pg_catalog.lower(pg_catalog.regexp_replace(
  pg_catalog.btrim(e.location), '[[:space:]]+', ' ', 'g'
));

alter table public.event_locations enable row level security;
revoke all on public.event_locations from public, anon, authenticated;
grant select on public.event_locations to authenticated;
create policy event_locations_read_authenticated on public.event_locations
  for select to authenticated using (true);

create function private.sync_event_location() returns trigger
language plpgsql set search_path = '' as $$
declare saved_location_id bigint;
begin
  if tg_op = 'UPDATE' and new.location is not distinct from old.location then
    new.location_id := old.location_id;
    return new;
  end if;

  insert into public.event_locations(name)
    values (pg_catalog.btrim(new.location))
    on conflict (normalized_name) do update
      set name = public.event_locations.name
    returning id into saved_location_id;
  new.location_id := saved_location_id;
  return new;
end;
$$;
revoke all on function private.sync_event_location() from public, anon, authenticated;

create trigger events_sync_location
  before insert or update of location on public.events
  for each row execute function private.sync_event_location();

create function private.create_event_location(p_name text) returns bigint
language plpgsql security definer set search_path = '' as $$
declare saved_id bigint; normalized text;
begin
  if not private.current_is_admin() then raise exception 'Admin required'; end if;
  p_name := pg_catalog.btrim(p_name);
  if p_name is null or p_name = '' then
    raise exception 'Location is required';
  end if;
  normalized := pg_catalog.lower(pg_catalog.regexp_replace(p_name, '[[:space:]]+', ' ', 'g'));
  insert into public.event_locations(name) values(p_name)
    on conflict (normalized_name) do nothing returning id into saved_id;
  if saved_id is null then
    select id into saved_id from public.event_locations where normalized_name=normalized;
  else
    perform private.write_audit_log('event_location.created','event_location',saved_id::text,
      pg_catalog.jsonb_build_object('name',p_name));
  end if;
  return saved_id;
end;
$$;

create function private.rename_event_location(p_id bigint,p_name text) returns void
language plpgsql security definer set search_path = '' as $$
declare old_name text;
begin
  if not private.current_is_admin() then raise exception 'Admin required'; end if;
  p_name := pg_catalog.btrim(p_name);
  if p_name is null or p_name = '' then
    raise exception 'Location is required';
  end if;
  select name into old_name from public.event_locations where id=p_id for update;
  if not found then raise exception 'Location not found'; end if;
  if old_name is distinct from p_name then
    update public.event_locations set name=p_name where id=p_id;
    perform private.write_audit_log('event_location.renamed','event_location',p_id::text,
      pg_catalog.jsonb_build_object('old_name',old_name,'new_name',p_name));
  end if;
end;
$$;

create function private.delete_event_location(p_id bigint) returns void
language plpgsql security definer set search_path = '' as $$
declare old_name text;
begin
  if not private.current_is_admin() then raise exception 'Admin required'; end if;
  select name into old_name from public.event_locations where id=p_id for update;
  if not found then raise exception 'Location not found'; end if;
  delete from public.event_locations where id=p_id;
  perform private.write_audit_log('event_location.deleted','event_location',p_id::text,
    pg_catalog.jsonb_build_object('name',old_name,
      'historical_events_preserved',true));
end;
$$;

create function public.create_event_location(p_name text) returns bigint
language sql security invoker set search_path = '' as $$
  select private.create_event_location(p_name)
$$;
create function public.rename_event_location(p_id bigint,p_name text) returns void
language sql security invoker set search_path = '' as $$
  select private.rename_event_location(p_id,p_name)
$$;
create function public.delete_event_location(p_id bigint) returns void
language sql security invoker set search_path = '' as $$
  select private.delete_event_location(p_id)
$$;

revoke all on function private.create_event_location(text),
  private.rename_event_location(bigint,text), private.delete_event_location(bigint),
  public.create_event_location(text), public.rename_event_location(bigint,text),
  public.delete_event_location(bigint) from public, anon, authenticated;
grant execute on function private.create_event_location(text),
  private.rename_event_location(bigint,text), private.delete_event_location(bigint),
  public.create_event_location(text), public.rename_event_location(bigint,text),
  public.delete_event_location(bigint) to authenticated;
