-- Forward-only upgrade: preserve existing IDs, memberships, signups and point history.
alter table public.officers
  add column auth_user_id uuid constraint officers_auth_user_id_fkey references auth.users(id),
  add constraint officers_auth_user_id_key unique (auth_user_id),
  add column application_role text not null default 'officer'
    constraint officers_application_role_check check (application_role in ('admin', 'officer'));

-- This capability already exists. Titles are controlled data, not authorization logic.
update public.positions set can_manage_branch_events =
  name in ('ICPC Lead', 'Intro Lead', 'Social Media Lead');

create table public.event_types (
  id bigint generated by default as identity primary key,
  name text not null constraint event_types_name_not_blank check (length(trim(name)) > 0),
  created_at timestamptz not null default now()
);
create unique index event_types_name_key on public.event_types (lower(trim(name)));
insert into public.event_types (name) values
  ('General'), ('Intro'), ('ICPC'), ('Meeting'), ('Social'), ('Workshop');
-- Preserve custom historical types too. Case/outer whitespace variants share one type.
insert into public.event_types (name)
  select distinct on (lower(trim(type))) trim(type)
  from public.events order by lower(trim(type)), id
  on conflict (lower(trim(name))) do nothing;
alter table public.events add column event_type_id bigint
  constraint events_event_type_id_fkey references public.event_types(id) on delete restrict;
update public.events e set event_type_id = t.id from public.event_types t
  where lower(trim(e.type)) = lower(trim(t.name));
-- Fails instead of discarding an unmapped historical row.
alter table public.events alter column event_type_id set not null;
drop function public.save_event(text,text,text,text,timestamptz,timestamptz,bigint[],bigint);
alter table public.events drop column type;
alter table public.events
  add column participation_points_per_hour_at_end numeric
    constraint events_participation_rate_check check (
      participation_points_per_hour_at_end > 0 and
      participation_points_per_hour_at_end not in ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)),
  add column slides_url text,
  add column meeting_notes_url text,
  add column flyer_status text constraint events_flyer_status_check
    check (flyer_status in ('not_started', 'in_progress', 'done')),
  add column flyer_assigned_to bigint constraint events_flyer_assigned_to_fkey references public.officers(id);
create index events_event_type_id_idx on public.events(event_type_id);
create index events_flyer_assigned_to_idx on public.events(flyer_assigned_to);

create table public.officer_warnings (
  id bigint generated by default as identity primary key,
  officer_id bigint not null references public.officers(id),
  reason text not null constraint officer_warnings_reason_not_blank check (length(trim(reason)) > 0),
  status text not null default 'pending'
    constraint officer_warnings_status_check check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now()
);
create index officer_warnings_officer_id_idx on public.officer_warnings(officer_id);
create table public.warning_approvals (
  warning_id bigint not null references public.officer_warnings(id) on delete cascade,
  approver_id uuid not null references auth.users(id),
  approver_role text not null constraint warning_approvals_role_check
    check (approver_role in ('President', 'Vice President')),
  decision text not null default 'pending'
    constraint warning_approvals_decision_check check (decision in ('pending', 'approved', 'rejected')),
  decided_at timestamptz,
  primary key (warning_id, approver_id)
);
create index warning_approvals_approver_id_idx on public.warning_approvals(approver_id);

-- PK + fixed key permits at most one row, seeded here; no client deletion grant.
create table public.application_config (
  id integer primary key default 1 constraint application_config_single_row check (id = 1),
  participation_points_per_hour numeric not null constraint application_config_participation_rate_check
    check (participation_points_per_hour > 0 and participation_points_per_hour not in ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)),
  flyer_completion_points numeric not null constraint application_config_flyer_points_check
    check (flyer_completion_points >= 0 and flyer_completion_points not in ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)),
  updated_at timestamptz not null default now()
);
-- 1 preserves the POC default; 0 is a neutral flyer placeholder, not a club policy.
insert into public.application_config (id, participation_points_per_hour, flyer_completion_points) values (1, 1, 0);

-- Unknown non-null legacy actors abort the upgrade; never silently erase attribution.
alter table public.point_transactions
  add constraint point_transactions_created_by_fkey foreign key (created_by) references auth.users(id),
  add column removed_at timestamptz,
  add column removed_by uuid constraint point_transactions_removed_by_fkey references auth.users(id),
  drop constraint point_transactions_award_type_check,
  add constraint point_transactions_award_type_check check (award_type in ('participation', 'manual', 'correction', 'flyer')),
  add constraint point_transactions_flyer_event_required check (award_type <> 'flyer' or event_id is not null);
-- Both automatic-award indexes include removed rows, so a void is never regenerated.
create unique index one_flyer_award on public.point_transactions(event_id) where award_type = 'flyer';
create index point_transactions_created_by_idx on public.point_transactions(created_by);
create index point_transactions_removed_by_idx on public.point_transactions(removed_by);

create table public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id),
  action text not null constraint audit_logs_action_not_blank check (length(trim(action)) > 0),
  entity_type text not null constraint audit_logs_entity_type_not_blank check (length(trim(entity_type)) > 0),
  -- Text also represents composite entity keys; deliberately not a business-record FK.
  entity_id text not null constraint audit_logs_entity_id_not_blank check (length(trim(entity_id)) > 0),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index audit_logs_actor_id_idx on public.audit_logs(actor_id);

-- New workflow tables are closed until identity-aware policies arrive in PR 3.
alter table public.event_types enable row level security;
alter table public.officer_warnings enable row level security;
alter table public.warning_approvals enable row level security;
alter table public.application_config enable row level security;
alter table public.audit_logs enable row level security;
revoke all on public.event_types, public.officer_warnings, public.warning_approvals,
  public.application_config, public.audit_logs from public, anon, authenticated;
revoke all on sequence public.event_types_id_seq, public.officer_warnings_id_seq,
  public.audit_logs_id_seq from public, anon, authenticated;
create policy "TEMPORARY DEVELOPMENT read event types" on public.event_types for select to anon using (true);
grant select on public.event_types to anon;

-- Existing table-wide grants would otherwise expose the new role/identity, flyer,
-- snapshot and removal fields to anonymous writes. Preserve only the old POC writes.
revoke insert, update on public.officers from anon;
grant insert (name, utep_email, personal_email, position_id, classification, status),
  update (name, utep_email, personal_email, position_id, classification, status) on public.officers to anon;
revoke insert, update on public.events from anon;
grant insert (name, description, event_type_id, location, starts_at, ends_at, status),
  update (name, description, event_type_id, location, starts_at, ends_at, status) on public.events to anon;
revoke insert on public.point_transactions from anon;
grant insert (officer_id, event_id, points, reason, award_type, created_by) on public.point_transactions to anon;
alter policy "TEMPORARY DEVELOPMENT insert points" on public.point_transactions
  with check (created_by is null and removed_at is null and removed_by is null and award_type <> 'flyer');

create or replace function public.save_officer(
  p_name text, p_position_id bigint, p_status text, p_branch_ids bigint[],
  p_officer_id bigint default null, p_utep_email text default null,
  p_personal_email text default null, p_classification text default null
) returns bigint language plpgsql security invoker set search_path = '' as $$
declare
  saved_id bigint;
  university_email text := nullif(lower(trim(p_utep_email)), '');
  contact_email text := nullif(lower(trim(p_personal_email)), '');
  officer_classification text := nullif(trim(p_classification), '');
begin
  if coalesce(cardinality(p_branch_ids), 0) = 0 then
    raise exception 'Select at least one branch';
  end if;
  if p_officer_id is null then
    insert into public.officers (name,utep_email,personal_email,position_id,classification,status)
    values (trim(p_name),university_email,contact_email,p_position_id,officer_classification,p_status)
    returning id into saved_id;
  else
    update public.officers set name=trim(p_name),utep_email=university_email,
      personal_email=contact_email,position_id=p_position_id,
      classification=officer_classification,status=p_status
    where id=p_officer_id returning id into saved_id;
    if saved_id is null then raise exception 'Officer not found'; end if;
  end if;
  delete from public.officer_branches where officer_id=saved_id;
  insert into public.officer_branches (officer_id,branch_id)
  select saved_id, branch_id from unnest(p_branch_ids) as branch_id;
  return saved_id;
end;
$$;

create function public.save_event(
  p_name text, p_description text, p_event_type_id bigint, p_location text,
  p_starts_at timestamptz, p_ends_at timestamptz, p_branch_ids bigint[], p_event_id bigint default null
) returns bigint language plpgsql security invoker set search_path = '' as $$
declare saved_id bigint; current_event public.events;
begin
  if coalesce(cardinality(p_branch_ids),0)=0 then raise exception 'Select at least one branch'; end if;
  if p_event_id is null then
    insert into public.events(name,description,event_type_id,location,starts_at,ends_at)
    values(trim(p_name),p_description,p_event_type_id,nullif(trim(p_location),''),p_starts_at,p_ends_at)
    returning id into saved_id;
  else
    select * into current_event from public.events where id=p_event_id for update;
    if not found then raise exception 'Event not found'; end if;
    if current_event.starts_at<=now() or current_event.status='cancelled' then
      raise exception 'Only upcoming events can be edited';
    end if;
    update public.events set name=trim(p_name),description=p_description,event_type_id=p_event_type_id,
      location=nullif(trim(p_location),''),starts_at=p_starts_at,ends_at=p_ends_at
      where id=p_event_id returning id into saved_id;
  end if;
  delete from public.event_branches where event_id=saved_id;
  insert into public.event_branches(event_id,branch_id) select saved_id,branch_id from unnest(p_branch_ids) as branch_id;
  return saved_id;
end;
$$;
revoke all on function public.save_event(text,text,bigint,text,timestamptz,timestamptz,bigint[],bigint) from public, anon, authenticated;
grant execute on function public.save_event(text,text,bigint,text,timestamptz,timestamptz,bigint[],bigint) to anon;

create or replace view public.officer_point_totals with (security_invoker=true) as
  select o.id, o.name, coalesce(sum(p.points),0) as total_points
  from public.officers o left join public.point_transactions p
    on p.officer_id=o.id and p.removed_at is null group by o.id,o.name;
-- Keep the POC UTC half-year semantics; the coordinated America/Denver change is later work.
create or replace view public.dashboard_summary with (security_invoker=true) as
  with period as (
    select (date_trunc('year',now() at time zone 'UTC') +
      case when extract(month from now() at time zone 'UTC')>6 then interval '6 months' else interval '0 months' end)
      at time zone 'UTC' as starts_at
  )
  select (select count(*) from public.officers where status='active') as active_officer_count,
    (select count(*) from public.events where status<>'cancelled' and starts_at>now()) as upcoming_event_count,
    (select coalesce(sum(points),0) from public.point_transactions,period
      where removed_at is null and created_at>=period.starts_at and created_at<period.starts_at+interval '6 months') as half_year_points;
-- change_event_signup and process_completed_events do not use the old type column.
-- Keep their POC behavior/grants; processing already conflicts with removed participation rows.
